[package]
name = "shortbot"
version = "0.3.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { version = "0.15.6", features = ["yaml"] }
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.217", features = ["serde_derive"] }
teloxide = { version = "0.13.0", features = ["macros", "ctrlc_handler", "webhooks-axum"] }
tokio = {version = "1.8", features = ["rt-multi-thread", "macros"]}
serde_derive = "1.0"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.3.0"
pretty_assertions = "1.4.1"
rstest = "0.24.0"
toml = "0.8.19"
scraper = "0.22.0"
reqwest = { version = "0.12.12", features = ["json"] }
thiserror = "2.0.11"
sqlx = { version = "0.8", features = [ "runtime-tokio", "postgres", "macros", "uuid", "chrono" ] }
finance_ibex = "0.1.0-beta1"
finance_api = "0.1.0"
data_harvest = "0.2.1"
uuid = { version = "1.13.1", features = ["v4"] }
chrono = { version = "0.4.38", features = ["alloc", "std", "clock"] }
axum = "0.7.9"
