[package]
name = "shortbot"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
config = { version = "0.15.6", features = ["yaml"] }
secrecy = { version = "0.10.3", features = ["serde"] }
serde = { version = "1.0.217", features = ["serde_derive"] }
teloxide = { version = "0.12.2", features = ["macros", "ctrlc_handler"] }
tokio = {version = "1.8", features = ["rt-multi-thread", "macros"]}
serde_derive = "1.0"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = "0.3.0"
pretty_assertions = "1.4.1"
rstest = "0.24.0"
toml = "0.8.19"
scraper = "0.18.1"
date-rs = "0.1.2"
reqwest = { version = "0.12.4", features = ["json"] }
thiserror = "2.0.11"
