# Base configuration file.
# ------------------------
# These settings are applied unless environment variables override any of the
# following variables.

# Tracing level.
tracing_level = "info"

# Data path
data_path = "./data"

[application]
# Telegram API Token - override me!
api_token = "my_api_token"

