# Base configuration file.
# ------------------------
# These settings are applied unless environment variables override any of the
# following variables.

# Tracing level.
tracing_level = "info"

# Data path
data_path = "./data"

[application]
# Telegram API Token - override me!
api_token = "my_api_token"
http_server_host = "127.0.0.1"
http_server_port = "9601"
webhook_url = "base url"
webhook_path = "path"
webhook_token = "token"

[database]
questdb_host = "127.0.0.1"
questdb_port = 8812
questdb_user = "user"
questdb_password = "password"
mariadb_host = "127.0.0.1"
mariadb_port = 3306
mariadb_user = "root"
mariadb_password = "password"
mariadb_dbname = "shortbot"
mariadb_ssl_mode = false

[clientlib]
enable_cache = true
cache_queue_size = 10
cache_shards = 4
