name: Podman build & push

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
    build-push:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Use Podman Build and Push Action
              uses: Frozen-Tapestry/container-action@v1
              with:
                login_registry: ghcr.io
                login_username: ${{ github.actor }}
                login_password: ${{ secrets.REGISTRY_TOKEN }}
                dockerfile: ./Containerfile
                labels: io.containers.autoupdate=registry
                tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }} ghcr.io/${{ github.repository }}:latest
                extra_args: --annotation org.opencontainers.image.authors=Felipe\ Torres\ Gonzalez<admin@nubecita.eu> --annotation org.opencontainers.image.licenses=MPL-2.0 --annotation org.opencontainers.image.description=IbexShortBot\ Backend\ Microservice
                push: true
                security: |
                  --security-opt=seccomp=unconfined
                  --security-opt=apparmor=unconfined
