# This workflow is meant to be used only with commits to the main branch.

name: Rust CI Flow

on:
  push:
    branches: [ "main", "development" ]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'Cargo.**'
  pull_request:
    branches: [ "main", "development" ]
    paths:
      - 'src/**'
      - 'Dockerfile'
      - 'Cargo.**'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  SQLX_FEATURES: "mysql"
  SQLX_VERSION: "0.8.3"

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt clippy
      - name: Enforce formatting
        run: cargo fmt --check

  build:
    name: Check
    needs: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt clippy
      - name: Build
        run: SQLX_OFFLINE=true cargo check --future-incompat-report

  clippy:
    name: Clippy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt clippy
      - name: Linting
        run: SQLX_OFFLINE=true cargo clippy --no-deps -- -D warnings

  test:
    name: Test
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: getong/mariadb-action@v1.11
        with:
           mysql root password: "password"
           mysql database: "shortbot"
           mysql user: "root"
           mysql password: "password"
      - name: Install SQLx-cli
        run:
            cargo install sqlx-cli
            --version=${{ env.SQLX_VERSION }}
            --features ${{ env.SQLX_FEATURES }}
            --no-default-features
            --locked
      - name: Migrate database
        run: sqlx migrate run
      - name: Tests
        run: cargo test
